# Installation

MLHub runs on Ubuntu LTS (Long Term Supported). Ubuntu can be readily
installed on Windows 10 within the Windows Subsystem for Linux. It is
also available as the operating system of choice from the Raspberry Pi
to any desktop or laptop where it is easy to install. It is also
available as the operating system of a virtual machine, from the
Hyper-V gallery on Windows, for example (enable Hyper-V and choose
Ubuntu). For MacOS X one can use Parallels or Virtual Box to install
Ubuntu. It is also probably the most widely deployed operating system
on cloud servers.

The various options for installing Ubuntu are covered in the following
sections of this chapter, finishing with the installation of MLHub
itself in Section \@ref(installing-mlhub).

All of the curated models that are registered with MLHub are tested
against Ubuntu LTS.

## Installing Ubuntu WSL

The Windows Subsystem for Linux (WSL) is available as a feature on
Windows 10. Out-of-the-box WSL supports Ubuntu running within
Windows. This is the simplest option if you have Windows 10 (1709 or
later) installed (see Settings -> System -> About). It also requires
the installation of XMing or VcXsrv. Microsoft also released WSLv2 in
May 2020 to incorporate the Linux kernel directly within Windows, so
as to deliver significant performance gains and support more
applications. However WSLv2 is not currently recommended due to its
limited access to Windows file systems from Ubuntu.

To get started

+ Install XMing on Windows (download, run, and choose the defaults for
  the installation).
+ Go to "Turn Windows Features On or Off" (Control Panel -> Programs
  -> Programs and Features), tick on the box ‘Windows Subsystem for
  Linux’ to install WSL and reboot.
+ Go to Microsoft Store and search for the latest Ubuntu distribution
  to install.
+ Launch Ubuntu from the Start menu or else type the command “ubuntu”
  in the Powershell.
+ For GUI applications run the command $ export DISPLAY=:0 in the
  Ubuntu terminal window.

## Installing Ubuntu Desktop

Your best choice is to install the latest Ubuntu LTS on your own computer
as the base operating system. Many people run Ubuntu rather than
Windows so you will be in good company. 

## Installing Ubuntu in the Cloud

Most cloud providers support Ubuntu. It is possible to fire up a
Ubuntu server in the cloud for just $5 per month. Many cloud vendors
will provide free credit (from $100 to $200) to get you started.

For example, you can get free credit ($200) from Microsoft to trial
Azure.  After signing up with Azure, the Azure portal will allow you
to create a new Ubuntu 20.04 LTS server, creating a new resource group
for it, providing a name for the virtual machine, a user name and a
password, choosing a location (e.g., westus2), opening network port 22
for ssh connectivity, and choosing a machine size to suit your
needs. Once created go to the portal and provide a DNS name from the
overview page’s, DNS link. Connect to the server using `r
Command(ssh)` from a terminal to the DNS name, set the server up as in
Section \@ref(installing-mlhub), then connect to the server using X2Go
on your own desktop.

Connection to a remote server will often be using X2Go. This usually
requires the MATE desktop to be installed on the cloud server:

```bash
$ wajig install ubuntu-mate-desktop
```

## Installing Ubuntu VirtualBox

## Installing MLHub

`r CiteDate(20200220)` `r Link("MLHub","https://mlhub.ai")` is
specifically developed and built to run on Ubuntu, implemented in
Python3. MLHub can be installed from the
[PyPI](https://pypi.org/project/mlhub/) Python library repository. If
your Ubuntu platform already has Python3 installed, including pip,
then it is a single command to install mlhub:

```bash
$ pip3 install mlhub
```

If you have just set up a new Ubuntu server, or you have not
previously had Python installed, the following steps will be useful.
To simplify using the Ubuntu system we will use the `r Command(wajig)`
system administration suite. `r Package(wajig, "Wajig")` is available
from the Debian and Ubuntu repositories with the latest updates
available from `r Link("PyPI","https://pypi.org/project/wajig/")`. 
Installation of `r Package(wajig)` will usually take less than 5 minutes.

```bash
$ sudo apt update
$ sudo apt upgrade
$ sudo apt install wajig
$ wajig update 
$ wajig upgrade 
$ wajig install python3-pip
$ pip3 install wajig
```

Be sure to log out and log back in after the `r Command(pip3)` install
so that the system will notice your local installations.

Now we are ready to install and configure MLHub:

```bash
$ pip3 install mlhub
$ ml configure
```

If you now find that the `r Command(ml)` command is not found then you
may like to log out and back in again. This will refresh the PATH
where commands are found. The default in Ubuntu 20.04 LTS is that the
path will include `~/.local/bin` if it exists, which won't be the
case for the first time. `r Command(pip3, "Pip3")` will install the
`r Command(ml)` command there and this is checked at login. If all else
fails then the following could be useful (but not usually required):

```bash
$ echo 'PATH=~/.local/bin:$PATH' >> ~/.bashrc
```

MLHub exposes a github repository as a collection of quickly
accessible and ready to run, explore, rebuild, and even deploy,
pre-built machine learning models and data science technology.  The
models and technology are accessed and managed using the ml command
from the mlhub package available for quick installation from pypi. A
growing number of machine learning models and data science technology
are becoming available, as well as cloud based services.

The **configure** of `r Command(ml)` as above will install quite a
comprehensive collection of AI technology to have your computer
AI-ready. This will include several hundred packages (mostly small)
that are downloaded and installed. For each of the major packages you
will be asked to confirm that it is okay to install it. This could
take up to 5 minutes.

This will install quite a collection of free and open source packages
that begins to form a foundation for doing AI and ML and Data Science
on Ubuntu. Included is the `r Link("R Statistical Software", "https://r-project.org")` package.

As the instructions will suggest, run the following to immediately
turn on tab expansion for mlhub commands and model names. This will be
available anyhow on the next login.

```bash
$ source /etc/bash_completion.d/ml.bash
```
